language: ruby
rvm:
- 2.2
script: bundle exec jekyll build
notifications:
  slack:
    secure: NNHI9s7P54yHw3AgvApmmxv2uFubEM5z1dypbhhfDOWHkZ9PdvcV1zmlLaumMma8n5SmwDYrUdYooGNvbeCcpCgeI6M/Di3TYlpDW74VMPL+7agiicWjusozRmIGrrv9wUZchqgZDD+lWFuCu+1eiJOWT45/Qb8tq8R40TWOLd0l3wSxCSQxOtjyqXNawvNVLSUaveUZy+bEQDuJ7bG0CEI3RQzFxmYKNdKqtuftmcTnZwT2K/BlhELKsv7csdPJgoe7SuMSSCvKul7aePfvp7D6EEvoyTw8twofHlBJE98CF6OmLPyQyU5YBme1fdTALYaqvkRhYYyXKHrybYWZn9qZyjLTrt8gRnU650yTDrvaAQZw1IZw4hbgGZ82sXpP7TCR0wlA/9JVasjqFnSylkN6hJghkbLoT+Ix6QVCC6HrCsx2iMLg8bTMAlmpuqCAJD2k/uZ3j6wFtVnUSxV/lEP+cyQ+hH798OSLTy3noMsKzIId3k9hQi6PdqaguZzN31+sAilZK7rkZwY050wb5WTIcMVgA2693BnwhWHvVX66/VNoFTZL32LiJ7iVAGea8jKHwt6MPUle6I1pDYTsi6QWbNiTxY7/SgakT6Qr9rirx89WREDD9f/yreBZ4L9ovtuRb5A7iG6GWUaxI81g01GwrCAZdOgWi8JEVUpybOM=
