# Site settings
title: Nubis Project
email: gozer@mozilla.com
description: > # this means to ignore newlines until "baseurl:"
  Mozilla, going to the Cloud! Are you coming?
github_username:  nubisproject

# Build settings
markdown: kramdown
